# Generated by Django 5.0.6 on 2024-11-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.RemoveField(
            model_name='report',
            name='conversation',
        ),
        migrations.AddField(
            model_name='report',
            name='conversation_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='outcome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
