# Generated by Django 5.0.6 on 2024-11-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_remove_report_category_remove_report_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='unique_user_id',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
    ]
