# Generated by Django 5.0.6 on 2024-12-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_remove_report_user_report_unique_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='conversation_link',
            field=models.URLField(default=1, max_length=2048, unique=True),
            preserve_default=False,
        ),
    ]
